import { Pokemon } from './types';

export const pokemonList: Pokemon[] = [
    // Gen 1
    { id: "venusaur", name: "Venusaur", spe: 80, ability: 'chlorophyll', spriteIndex: 0 },
    { id: "mega venusaur", name: "Mega Venusaur", spe: 80, baseSpecies: "venusaur", spriteIndex: 1 },
    { id: "charizard", name: "Charizard", spe: 100, spriteIndex: 2 },
    { id: "mega charizard x", name: "Mega Charizard X", spe: 100, baseSpecies: "charizard", spriteIndex: 3 },
    { id: "mega charizard y", name: "Mega Charizard Y", spe: 100, baseSpecies: "charizard", spriteIndex: 4 },
    { id: "blastoise", name: "Blastoise", spe: 78, spriteIndex: 5 },
    { id: "mega blastoise", name: "Mega Blastoise", spe: 78, baseSpecies: "blastoise", spriteIndex: 6 },
    { id: "beedrill", name: "Beedrill", spe: 75, spriteIndex: 7 },
    { id: "mega beedrill", name: "Mega Beedrill", spe: 145, baseSpecies: "beedrill", spriteIndex: 8 },
    { id: "pidgeot", name: "Pidgeot", spe: 101, spriteIndex: 9 },
    { id: "mega pidgeot", name: "Mega Pidgeot", spe: 121, baseSpecies: "pidgeot", spriteIndex: 10 },
    { id: "arbok", name: "Arbok", spe: 80, spriteIndex: 11 },
    { id: "pikachu", name: "Pikachu", spe: 90, spriteIndex: 12 },
    { id: "raichu", name: "Raichu", spe: 110, spriteIndex: 13 },
    { id: "alolan raichu", name: "Alolan Raichu", spe: 110, ability: 'surge-surfer', baseSpecies: "raichu", spriteIndex: 14 },
    { id: "mega raichu x", name: "Mega Raichu X", spe: 110, baseSpecies: "raichu" },
    { id: "mega raichu y", name: "Mega Raichu Y", spe: 130, baseSpecies: "raichu" },
    { id: "clefable", name: "Clefable", spe: 60, spriteIndex: 15 },
    { id: "mega clefable", name: "Mega Clefable", spe: 70, baseSpecies: "clefable", spriteIndex: 16 },
    { id: "ninetales", name: "Ninetales", spe: 100, spriteIndex: 17 },
    { id: "alolan ninetales", name: "Alolan Ninetales", spe: 109, baseSpecies: "ninetales", spriteIndex: 18 },
    { id: "arcanine", name: "Arcanine", spe: 95, spriteIndex: 19 },
    { id: "hisuian arcanine", name: "Hisuian Arcanine", spe: 90, baseSpecies: "arcanine", spriteIndex: 20 },
    { id: "alakazam", name: "Alakazam", spe: 120, spriteIndex: 21 },
    { id: "mega alakazam", name: "Mega Alakazam", spe: 150, baseSpecies: "alakazam", spriteIndex: 22 },
    { id: "machamp", name: "Machamp", spe: 55, spriteIndex: 23 },
    { id: "victreebel", name: "Victreebel", spe: 70, ability: 'chlorophyll', spriteIndex: 24 },
    { id: "mega victreebel", name: "Mega Victreebel", spe: 70, baseSpecies: "victreebel", spriteIndex: 25 },
    { id: "slowbro", name: "Slowbro", spe: 30, spriteIndex: 26 },
    { id: "mega slowbro", name: "Mega Slowbro", spe: 30, baseSpecies: "slowbro", spriteIndex: 27 },
    { id: "galarian slowbro", name: "Galarian Slowbro", spe: 30, baseSpecies: "slowbro", spriteIndex: 28 },
    { id: "gengar", name: "Gengar", spe: 110, spriteIndex: 29 },
    { id: "mega gengar", name: "Mega Gengar", spe: 130, baseSpecies: "gengar", spriteIndex: 30 },
    { id: "kangaskhan", name: "Kangaskhan", spe: 90, spriteIndex: 31 },
    { id: "mega kangaskhan", name: "Mega Kangaskhan", spe: 100, baseSpecies: "kangaskhan", spriteIndex: 32 },
    { id: "starmie", name: "Starmie", spe: 115, spriteIndex: 33 },
    { id: "mega starmie", name: "Mega Starmie", spe: 120, baseSpecies: "starmie", spriteIndex: 34 },
    { id: "pinsir", name: "Pinsir", spe: 85, spriteIndex: 35 },
    { id: "mega pinsir", name: "Mega Pinsir", spe: 105, baseSpecies: "pinsir", spriteIndex: 36 },
    { id: "tauros", name: "Tauros", spe: 110, spriteIndex: 37 },
    { id: "tauros-paldea-combat", name: "Tauros-Paldea-Combat", spe: 100, baseSpecies: "tauros", spriteIndex: 38 },
    { id: "tauros-paldea-blaze", name: "Tauros-Paldea-Blaze", spe: 100, baseSpecies: "tauros", spriteIndex: 39 },
    { id: "tauros-paldea-aqua", name: "Tauros-Paldea-Aqua", spe: 100, baseSpecies: "tauros", spriteIndex: 40 },
    { id: "gyarados", name: "Gyarados", spe: 81, spriteIndex: 41 },
    { id: "mega gyarados", name: "Mega Gyarados", spe: 81, baseSpecies: "gyarados", spriteIndex: 42 },
    { id: "ditto", name: "Ditto", spe: 48, spriteIndex: 43 },
    { id: "vaporeon", name: "Vaporeon", spe: 65, spriteIndex: 44 },
    { id: "jolteon", name: "Jolteon", spe: 130, ability: 'quick-feet', spriteIndex: 45 },
    { id: "flareon", name: "Flareon", spe: 65, spriteIndex: 46 },
    { id: "aerodactyl", name: "Aerodactyl", spe: 130, spriteIndex: 47 },
    { id: "mega aerodactyl", name: "Mega Aerodactyl", spe: 150, baseSpecies: "aerodactyl", spriteIndex: 48 },
    { id: "snorlax", name: "Snorlax", spe: 30, spriteIndex: 49 },
    { id: "dragonite", name: "Dragonite", spe: 80, spriteIndex: 50 },
    { id: "mega dragonite", name: "Mega Dragonite", spe: 100, baseSpecies: "dragonite", spriteIndex: 51 },
    { id: "vileplume", name: "Vileplume", spe: 50, ability: 'chlorophyll' },

    // Gen 2
    { id: "meganium", name: "Meganium", spe: 80, spriteIndex: 52 },
    { id: "mega meganium", name: "Mega Meganium", spe: 80, baseSpecies: "meganium", spriteIndex: 53 },
    { id: "typhlosion", name: "Typhlosion", spe: 100, spriteIndex: 54 },
    { id: "hisuian typhlosion", name: "Hisuian Typhlosion", spe: 95, baseSpecies: "typhlosion", spriteIndex: 55 },
    { id: "feraligatr", name: "Feraligatr", spe: 78, spriteIndex: 56 },
    { id: "mega feraligatr", name: "Mega Feraligatr", spe: 78, baseSpecies: "feraligatr", spriteIndex: 57 },
    { id: "ariados", name: "Ariados", spe: 40, spriteIndex: 58 },
    { id: "ampharos", name: "Ampharos", spe: 55, spriteIndex: 59 },
    { id: "mega ampharos", name: "Mega Ampharos", spe: 45, baseSpecies: "ampharos", spriteIndex: 60 },
    { id: "azumarill", name: "Azumarill", spe: 50, spriteIndex: 61 },
    { id: "politoed", name: "Politoed", spe: 70, spriteIndex: 62 },
    { id: "espeon", name: "Espeon", spe: 110, spriteIndex: 63 },
    { id: "umbreon", name: "Umbreon", spe: 65, spriteIndex: 64 },
    { id: "slowking", name: "Slowking", spe: 30, spriteIndex: 65 },
    { id: "galarian slowking", name: "Galarian Slowking", spe: 30, baseSpecies: "slowking", spriteIndex: 66 },
    { id: "forretress", name: "Forretress", spe: 40, spriteIndex: 67 },
    { id: "steelix", name: "Steelix", spe: 30, spriteIndex: 68 },
    { id: "mega steelix", name: "Mega Steelix", spe: 30, baseSpecies: "steelix", spriteIndex: 69 },
    { id: "scizor", name: "Scizor", spe: 65, spriteIndex: 70 },
    { id: "mega scizor", name: "Mega Scizor", spe: 75, baseSpecies: "scizor", spriteIndex: 71 },
    { id: "heracross", name: "Heracross", spe: 85, spriteIndex: 72 },
    { id: "mega heracross", name: "Mega Heracross", spe: 75, baseSpecies: "heracross", spriteIndex: 73 },
    { id: "skarmory", name: "Skarmory", spe: 70, spriteIndex: 74 },
    { id: "mega skarmory", name: "Mega Skarmory", spe: 110, baseSpecies: "skarmory", spriteIndex: 75 },
    { id: "houndoom", name: "Houndoom", spe: 95, spriteIndex: 76 },
    { id: "mega houndoom", name: "Mega Houndoom", spe: 115, baseSpecies: "houndoom", spriteIndex: 77 },
    { id: "tyranitar", name: "Tyranitar", spe: 61, spriteIndex: 78 },
    { id: "mega tyranitar", name: "Mega Tyranitar", spe: 71, baseSpecies: "tyranitar", spriteIndex: 79 },
    { id: "qwilfish", name: "Qwilfish", spe: 85, ability: 'swift-swim' },

    // Gen 3
    { id: "pelipper", name: "Pelipper", spe: 65, spriteIndex: 80 },
    { id: "gardevoir", name: "Gardevoir", spe: 80, spriteIndex: 81 },
    { id: "mega gardevoir", name: "Mega Gardevoir", spe: 100, baseSpecies: "gardevoir", spriteIndex: 82 },
    { id: "sableye", name: "Sableye", spe: 50, spriteIndex: 83 },
    { id: "mega sableye", name: "Mega Sableye", spe: 20, baseSpecies: "sableye", spriteIndex: 84 },
    { id: "aggron", name: "Aggron", spe: 50, spriteIndex: 85 },
    { id: "mega aggron", name: "Mega Aggron", spe: 50, baseSpecies: "aggron", spriteIndex: 86 },
    { id: "medicham", name: "Medicham", spe: 80, spriteIndex: 87 },
    { id: "mega medicham", name: "Mega Medicham", spe: 100, baseSpecies: "medicham", spriteIndex: 88 },
    { id: "manectric", name: "Manectric", spe: 105, spriteIndex: 89 },
    { id: "mega manectric", name: "Mega Manectric", spe: 135, baseSpecies: "manectric", spriteIndex: 90 },
    { id: "sharpedo", name: "Sharpedo", spe: 95, spriteIndex: 91 },
    { id: "mega sharpedo", name: "Mega Sharpedo", spe: 105, baseSpecies: "sharpedo", spriteIndex: 92 },
    { id: "camerupt", name: "Camerupt", spe: 40, spriteIndex: 93 },
    { id: "mega camerupt", name: "Mega Camerupt", spe: 20, baseSpecies: "camerupt", spriteIndex: 94 },
    { id: "torkoal", name: "Torkoal", spe: 20, spriteIndex: 95 },
    { id: "altaria", name: "Altaria", spe: 80, spriteIndex: 96 },
    { id: "mega altaria", name: "Mega Altaria", spe: 80, baseSpecies: "altaria", spriteIndex: 97 },
    { id: "milotic", name: "Milotic", spe: 81, spriteIndex: 98 },
    { id: "castform", name: "Castform", spe: 70, spriteIndex: 99 },
    { id: "castform-sunny", name: "Castform-Sunny", spe: 70, baseSpecies: "castform", spriteIndex: 100 },
    { id: "castform-rainy", name: "Castform-Rainy", spe: 70, baseSpecies: "castform", spriteIndex: 101 },
    { id: "castform-snowy", name: "Castform-Snowy", spe: 70, baseSpecies: "castform", spriteIndex: 102 },
    { id: "banette", name: "Banette", spe: 65, spriteIndex: 103 },
    { id: "mega banette", name: "Mega Banette", spe: 75, baseSpecies: "banette", spriteIndex: 104 },
    { id: "chimecho", name: "Chimecho", spe: 65, spriteIndex: 105 },
    { id: "mega chimecho", name: "Mega Chimecho", spe: 65, baseSpecies: "chimecho", spriteIndex: 106 },
    { id: "absol", name: "Absol", spe: 75, spriteIndex: 107 },
    { id: "mega absol", name: "Mega Absol", spe: 115, baseSpecies: "absol", spriteIndex: 108 },
    { id: "glalie", name: "Glalie", spe: 80, spriteIndex: 109 },
    { id: "mega glalie", name: "Mega Glalie", spe: 100, baseSpecies: "glalie", spriteIndex: 110 },
    { id: "sceptile", name: "Sceptile", spe: 120, ability: 'unburden' },
    { id: "mega sceptile", name: "Mega Sceptile", spe: 145, baseSpecies: "sceptile" },
    { id: "blaziken", name: "Blaziken", spe: 80 },
    { id: "mega blaziken", name: "Mega Blaziken", spe: 100, baseSpecies: "blaziken" },
    { id: "swampert", name: "Swampert", spe: 60 },
    { id: "mega swampert", name: "Mega Swampert", spe: 70, baseSpecies: "swampert" },
    { id: "mawile", name: "Mawile", spe: 50 },
    { id: "mega mawile", name: "Mega Mawile", spe: 50, baseSpecies: "mawile" },
    { id: "metagross", name: "Metagross", spe: 70 },
    { id: "mega metagross", name: "Mega Metagross", spe: 110, baseSpecies: "metagross" },

    // Gen 4
    { id: "torterra", name: "Torterra", spe: 56, spriteIndex: 111 },
    { id: "infernape", name: "Infernape", spe: 108, spriteIndex: 112 },
    { id: "empoleon", name: "Empoleon", spe: 60, spriteIndex: 113 },
    { id: "luxray", name: "Luxray", spe: 70, spriteIndex: 114 },
    { id: "roserade", name: "Roserade", spe: 90, spriteIndex: 115 },
    { id: "rampardos", name: "Rampardos", spe: 58, spriteIndex: 116 },
    { id: "bastiodon", name: "Bastiodon", spe: 30, spriteIndex: 117 },
    { id: "lopunny", name: "Lopunny", spe: 105, spriteIndex: 118 },
    { id: "mega lopunny", name: "Mega Lopunny", spe: 135, baseSpecies: "lopunny", spriteIndex: 119 },
    { id: "spiritomb", name: "Spiritomb", spe: 35, spriteIndex: 120 },
    { id: "garchomp", name: "Garchomp", spe: 102, spriteIndex: 121 },
    { id: "mega garchomp", name: "Mega Garchomp", spe: 92, baseSpecies: "garchomp", spriteIndex: 122 },
    { id: "lucario", name: "Lucario", spe: 90, spriteIndex: 123 },
    { id: "mega lucario", name: "Mega Lucario", spe: 112, baseSpecies: "lucario", spriteIndex: 124 },
    { id: "hippowdon", name: "Hippowdon", spe: 47, spriteIndex: 125 },
    { id: "toxicroak", name: "Toxicroak", spe: 85, spriteIndex: 126 },
    { id: "abomasnow", name: "Abomasnow", spe: 60, spriteIndex: 127 },
    { id: "mega abomasnow", name: "Mega Abomasnow", spe: 30, baseSpecies: "abomasnow", spriteIndex: 128 },
    { id: "weavile", name: "Weavile", spe: 125, spriteIndex: 129 },
    { id: "rhyperior", name: "Rhyperior", spe: 40, spriteIndex: 130 },
    { id: "leafeon", name: "Leafeon", spe: 95, ability: 'chlorophyll', spriteIndex: 131 },
    { id: "glaceon", name: "Glaceon", spe: 65, spriteIndex: 132 },
    { id: "gliscor", name: "Gliscor", spe: 95, spriteIndex: 133 },
    { id: "mamoswine", name: "Mamoswine", spe: 80, spriteIndex: 134 },
    { id: "gallade", name: "Gallade", spe: 80, spriteIndex: 135 },
    { id: "mega gallade", name: "Mega Gallade", spe: 110, baseSpecies: "gallade", spriteIndex: 136 },
    { id: "froslass", name: "Froslass", spe: 110, spriteIndex: 137 },
    { id: "mega froslass", name: "Mega Froslass", spe: 120, baseSpecies: "froslass", spriteIndex: 138 },
    { id: "rotom", name: "Rotom", spe: 91, spriteIndex: 139 },
    { id: "rotom-heat", name: "Rotom-Heat", spe: 86, baseSpecies: "rotom", spriteIndex: 140 },
    { id: "rotom-wash", name: "Rotom-Wash", spe: 86, baseSpecies: "rotom", spriteIndex: 141 },
    { id: "rotom-frost", name: "Rotom-Frost", spe: 86, baseSpecies: "rotom", spriteIndex: 142 },
    { id: "rotom-fan", name: "Rotom-Fan", spe: 86, baseSpecies: "rotom", spriteIndex: 143 },
    { id: "rotom-mow", name: "Rotom-Mow", spe: 86, baseSpecies: "rotom", spriteIndex: 144 },
    { id: "staraptor", name: "Staraptor", spe: 100 },
    { id: "mega staraptor", name: "Mega Staraptor", spe: 110, baseSpecies: "staraptor" },

    // Gen 5
    { id: "serperior", name: "Serperior", spe: 113, spriteIndex: 145 },
    { id: "emboar", name: "Emboar", spe: 65, spriteIndex: 146 },
    { id: "mega emboar", name: "Mega Emboar", spe: 75, baseSpecies: "emboar", spriteIndex: 147 },
    { id: "samurott", name: "Samurott", spe: 70, spriteIndex: 148 },
    { id: "hisuian samurott", name: "Hisuian Samurott", spe: 85, baseSpecies: "samurott", spriteIndex: 149 },
    { id: "watchog", name: "Watchog", spe: 77, spriteIndex: 150 },
    { id: "liepard", name: "Liepard", spe: 106, ability: 'unburden', spriteIndex: 151 },
    { id: "simisage", name: "Simisage", spe: 101, spriteIndex: 152 },
    { id: "simisear", name: "Simisear", spe: 101, spriteIndex: 153 },
    { id: "simipour", name: "Simipour", spe: 101, spriteIndex: 154 },
    { id: "excadrill", name: "Excadrill", spe: 88, ability: 'sand-rush', spriteIndex: 155 },
    { id: "mega excadrill", name: "Mega Excadrill", spe: 103, baseSpecies: "excadrill", spriteIndex: 156 },
    { id: "audino", name: "Audino", spe: 50, spriteIndex: 157 },
    { id: "mega audino", name: "Mega Audino", spe: 50, baseSpecies: "audino", spriteIndex: 158 },
    { id: "conkeldurr", name: "Conkeldurr", spe: 45, spriteIndex: 159 },
    { id: "whimsicott", name: "Whimsicott", spe: 116, ability: 'chlorophyll', spriteIndex: 160 },
    { id: "krookodile", name: "Krookodile", spe: 92, spriteIndex: 161 },
    { id: "cofagrigus", name: "Cofagrigus", spe: 30, spriteIndex: 162 },
    { id: "garbodor", name: "Garbodor", spe: 75, spriteIndex: 163 },
    { id: "zoroark", name: "Zoroark", spe: 105, spriteIndex: 164 },
    { id: "hisuian zoroark", name: "Hisuian Zoroark", spe: 110, baseSpecies: "zoroark", spriteIndex: 165 },
    { id: "reuniclus", name: "Reuniclus", spe: 30, spriteIndex: 166 },
    { id: "vanilluxe", name: "Vanilluxe", spe: 79, spriteIndex: 167 },
    { id: "emolga", name: "Emolga", spe: 103, spriteIndex: 168 },
    { id: "chandelure", name: "Chandelure", spe: 80, spriteIndex: 169 },
    { id: "mega chandelure", name: "Mega Chandelure", spe: 90, baseSpecies: "chandelure", spriteIndex: 170 },
    { id: "beartic", name: "Beartic", spe: 50, ability: ['swift-swim', 'slush-rush'], spriteIndex: 171 },
    { id: "stunfisk", name: "Stunfisk", spe: 32, spriteIndex: 172 },
    { id: "galarian stunfisk", name: "Galarian Stunfisk", spe: 32, baseSpecies: "stunfisk", spriteIndex: 173 },
    { id: "golurk", name: "Golurk", spe: 55, spriteIndex: 174 },
    { id: "mega golurk", name: "Mega Golurk", spe: 55, baseSpecies: "golurk", spriteIndex: 175 },
    { id: "hydreigon", name: "Hydreigon", spe: 98, spriteIndex: 176 },
    { id: "volcarona", name: "Volcarona", spe: 100, spriteIndex: 177 },
    { id: "musharna", name: "Musharna", spe: 29 },
    { id: "scrafty", name: "Scrafty", spe: 58 },
    { id: "mega scrafty", name: "Mega Scrafty", spe: 68, baseSpecies: "scrafty" },
    { id: "scolipede", name: "Scolipede", spe: 112 },
    { id: "mega scolipede", name: "Mega Scolipede", spe: 62, baseSpecies: "scolipede" },
    { id: "eelektross", name: "Eelektross", spe: 50 },
    { id: "mega eelektross", name: "Mega Eelektross", spe: 80, baseSpecies: "eelektross" },

    // Gen 6
    { id: "chesnaught", name: "Chesnaught", spe: 64, spriteIndex: 178 },
    { id: "mega chesnaught", name: "Mega Chesnaught", spe: 44, baseSpecies: "chesnaught", spriteIndex: 179 },
    { id: "delphox", name: "Delphox", spe: 104, spriteIndex: 180 },
    { id: "mega delphox", name: "Mega Delphox", spe: 134, baseSpecies: "delphox", spriteIndex: 181 },
    { id: "greninja", name: "Greninja", spe: 122, spriteIndex: 182 },
    { id: "mega greninja", name: "Mega Greninja", spe: 142, baseSpecies: "greninja", spriteIndex: 183 },
    { id: "diggersby", name: "Diggersby", spe: 78, spriteIndex: 184 },
    { id: "talonflame", name: "Talonflame", spe: 126, spriteIndex: 185 },
    { id: "vivillon", name: "Vivillon", spe: 89, spriteIndex: 186 },
    { id: "floette-eternal", name: "Floette-Eternal", spe: 92, spriteIndex: 206 },
    { id: "mega floette", name: "Mega Floette", spe: 102, baseSpecies: "floette-eternal", spriteIndex: 207 },
    { id: "florges", name: "Florges", spe: 75, spriteIndex: 208 },
    { id: "pangoro", name: "Pangoro", spe: 58, spriteIndex: 213 },
    { id: "furfrou", name: "Furfrou", spe: 102, spriteIndex: 214 },
    { id: "meowstic", name: "Meowstic", spe: 104, spriteIndex: 224 },
    { id: "meowstic-f", name: "Meowstic-F", spe: 104, baseSpecies: "meowstic", spriteIndex: 225 },
    { id: "mega meowstic", name: "Mega Meowstic", spe: 124, baseSpecies: "meowstic", spriteIndex: 226 },
    { id: "aegislash", name: "Aegislash", spe: 60, spriteIndex: 227 },
    { id: "aegislash-blade", name: "Aegislash-Blade", spe: 60, baseSpecies: "aegislash", spriteIndex: 228 },
    { id: "aromatisse", name: "Aromatisse", spe: 29, spriteIndex: 229 },
    { id: "slurpuff", name: "Slurpuff", spe: 72, ability: 'unburden', spriteIndex: 230 },
    { id: "clawitzer", name: "Clawitzer", spe: 59, spriteIndex: 231 },
    { id: "heliolisk", name: "Heliolisk", spe: 109, spriteIndex: 232 },
    { id: "tyrantrum", name: "Tyrantrum", spe: 71, spriteIndex: 233 },
    { id: "aurorus", name: "Aurorus", spe: 58, spriteIndex: 234 },
    { id: "sylveon", name: "Sylveon", spe: 60, spriteIndex: 235 },
    { id: "hawlucha", name: "Hawlucha", spe: 118, ability: 'unburden', spriteIndex: 236 },
    { id: "mega hawlucha", name: "Mega Hawlucha", spe: 118, baseSpecies: "hawlucha", spriteIndex: 237 },
    { id: "dedenne", name: "Dedenne", spe: 101, spriteIndex: 238 },
    { id: "goodra", name: "Goodra", spe: 80, spriteIndex: 239 },
    { id: "hisuian goodra", name: "Hisuian Goodra", spe: 60, baseSpecies: "goodra", spriteIndex: 240 },
    { id: "klefki", name: "Klefki", spe: 75, spriteIndex: 241 },
    { id: "trevenant", name: "Trevenant", spe: 56, spriteIndex: 242 },
    { id: "gourgeist", name: "Gourgeist", spe: 84, spriteIndex: 243 },
    { id: "gourgeist-small", name: "Gourgeist-Small", spe: 99, baseSpecies: "gourgeist", spriteIndex: 244 },
    { id: "gourgeist-large", name: "Gourgeist-Large", spe: 69, baseSpecies: "gourgeist", spriteIndex: 245 },
    { id: "gourgeist-super", name: "Gourgeist-Super", spe: 54, baseSpecies: "gourgeist", spriteIndex: 246 },
    { id: "avalugg", name: "Avalugg", spe: 28, spriteIndex: 247 },
    { id: "hisuian avalugg", name: "Hisuian Avalugg", spe: 38, baseSpecies: "avalugg", spriteIndex: 248 },
    { id: "noivern", name: "Noivern", spe: 123, spriteIndex: 249 },
    { id: "pyroar", name: "Pyroar", spe: 106 },
    { id: "mega pyroar", name: "Mega Pyroar", spe: 126, baseSpecies: "pyroar" },
    { id: "malamar", name: "Malamar", spe: 73 },
    { id: "mega malamar", name: "Mega Malamar", spe: 88, baseSpecies: "malamar" },
    { id: "barbaracle", name: "Barbaracle", spe: 68 },
    { id: "mega barbaracle", name: "Mega Barbaracle", spe: 88, baseSpecies: "barbaracle" },
    { id: "dragalge", name: "Dragalge", spe: 44 },
    { id: "mega dragalge", name: "Mega Dragalge", spe: 44, baseSpecies: "dragalge" },

    // Gen 7
    { id: "decidueye", name: "Decidueye", spe: 70, spriteIndex: 250 },
    { id: "hisuian decidueye", name: "Hisuian Decidueye", spe: 60, baseSpecies: "decidueye", spriteIndex: 251 },
    { id: "incineroar", name: "Incineroar", spe: 60, spriteIndex: 252 },
    { id: "primarina", name: "Primarina", spe: 60, spriteIndex: 253 },
    { id: "toucannon", name: "Toucannon", spe: 60, spriteIndex: 254 },
    { id: "crabominable", name: "Crabominable", spe: 43, spriteIndex: 255 },
    { id: "mega crabominable", name: "Mega Crabominable", spe: 33, baseSpecies: "crabominable", spriteIndex: 256 },
    { id: "lycanroc", name: "Lycanroc", spe: 112, ability: 'sand-rush', spriteIndex: 257 },
    { id: "lycanroc-midnight", name: "Lycanroc-Midnight", spe: 82, baseSpecies: "lycanroc", spriteIndex: 258 },
    { id: "lycanroc-dusk", name: "Lycanroc-Dusk", spe: 110, baseSpecies: "lycanroc", spriteIndex: 259 },
    { id: "toxapex", name: "Toxapex", spe: 35, spriteIndex: 260 },
    { id: "mudsdale", name: "Mudsdale", spe: 35, spriteIndex: 261 },
    { id: "araquanid", name: "Araquanid", spe: 42, spriteIndex: 262 },
    { id: "salazzle", name: "Salazzle", spe: 117, spriteIndex: 263 },
    { id: "tsareena", name: "Tsareena", spe: 72, spriteIndex: 264 },
    { id: "oranguru", name: "Oranguru", spe: 60, spriteIndex: 265 },
    { id: "passimian", name: "Passimian", spe: 80, spriteIndex: 266 },
    { id: "mimikyu", name: "Mimikyu", spe: 96, spriteIndex: 267 },
    { id: "drampa", name: "Drampa", spe: 36, spriteIndex: 268 },
    { id: "mega drampa", name: "Mega Drampa", spe: 36, baseSpecies: "drampa", spriteIndex: 269 },
    { id: "kommo-o", name: "Kommo-o", spe: 85, spriteIndex: 270 },

    // Gen 8
    { id: "corviknight", name: "Corviknight", spe: 67, spriteIndex: 271 },
    { id: "flapple", name: "Flapple", spe: 70, spriteIndex: 272 },
    { id: "appletun", name: "Appletun", spe: 30, spriteIndex: 273 },
    { id: "sandaconda", name: "Sandaconda", spe: 71, spriteIndex: 274 },
    { id: "polteageist", name: "Polteageist", spe: 70, spriteIndex: 275 },
    { id: "hatterene", name: "Hatterene", spe: 29, spriteIndex: 276 },
    { id: "mr. rime", name: "Mr. Rime", spe: 70, spriteIndex: 277 },
    { id: "runerigus", name: "Runerigus", spe: 30, spriteIndex: 278 },
    { id: "alcremie", name: "Alcremie", spe: 64, spriteIndex: 279 },
    { id: "morpeko", name: "Morpeko", spe: 97, spriteIndex: 288 },
    { id: "morpeko-hangry", name: "Morpeko-Hangry", spe: 97, baseSpecies: "morpeko", spriteIndex: 289 },
    { id: "dragapult", name: "Dragapult", spe: 142, spriteIndex: 290 },
    { id: "grimmsnarl", name: "Grimmsnarl", spe: 60 },
    { id: "falinks", name: "Falinks", spe: 75 },
    { id: "mega falinks", name: "Mega Falinks", spe: 100, baseSpecies: "falinks" },

    // Legends: Arceus
    { id: "wyrdeer", name: "Wyrdeer", spe: 65, spriteIndex: 291 },
    { id: "kleavor", name: "Kleavor", spe: 85, spriteIndex: 292 },
    { id: "basculegion", name: "Basculegion", spe: 78, ability: 'swift-swim', spriteIndex: 293 },
    { id: "basculegion-f", name: "Basculegion-F", spe: 78, ability: 'swift-swim', baseSpecies: "basculegion", spriteIndex: 294 },
    { id: "sneasler", name: "Sneasler", spe: 120, ability: 'unburden', spriteIndex: 295 },
    { id: "overqwil", name: "Overqwil", spe: 85, ability: 'swift-swim' },

    // Gen 9
    { id: "meowscarada", name: "Meowscarada", spe: 123, spriteIndex: 296 },
    { id: "skeledirge", name: "Skeledirge", spe: 66, spriteIndex: 297 },
    { id: "quaquaval", name: "Quaquaval", spe: 85, spriteIndex: 298 },
    { id: "maushold", name: "Maushold", spe: 111, spriteIndex: 300 },
    { id: "maushold-four", name: "Maushold-Four", spe: 111, baseSpecies: "maushold", spriteIndex: 301 },
    { id: "garganacl", name: "Garganacl", spe: 35, spriteIndex: 302 },
    { id: "armarouge", name: "Armarouge", spe: 75, spriteIndex: 303 },
    { id: "ceruledge", name: "Ceruledge", spe: 85, spriteIndex: 304 },
    { id: "bellibolt", name: "Bellibolt", spe: 45, spriteIndex: 305 },
    { id: "scovillain", name: "Scovillain", spe: 75, ability: 'chlorophyll', spriteIndex: 306 },
    { id: "mega scovillain", name: "Mega Scovillain", spe: 75, baseSpecies: "scovillain", spriteIndex: 307 },
    { id: "espathra", name: "Espathra", spe: 105, spriteIndex: 308 },
    { id: "tinkaton", name: "Tinkaton", spe: 94, spriteIndex: 309 },
    { id: "palafin", name: "Palafin", spe: 100, spriteIndex: 310 },
    { id: "palafin-hero", name: "Palafin-Hero", spe: 100, baseSpecies: "palafin", spriteIndex: 311 },
    { id: "orthworm", name: "Orthworm", spe: 65, spriteIndex: 312 },
    { id: "glimmora", name: "Glimmora", spe: 86, spriteIndex: 313 },
    { id: "mega glimmora", name: "Mega Glimmora", spe: 101, baseSpecies: "glimmora", spriteIndex: 314 },
    { id: "farigiraf", name: "Farigiraf", spe: 60, spriteIndex: 315 },
    { id: "kingambit", name: "Kingambit", spe: 50, spriteIndex: 316 },
    { id: "sinistcha", name: "Sinistcha", spe: 70, spriteIndex: 317 },
    { id: "archaludon", name: "Archaludon", spe: 85, spriteIndex: 318 },
    { id: "hydrapple", name: "Hydrapple", spe: 44, spriteIndex: 319 },
    { id: "houndstone", name: "Houndstone", spe: 68, ability: 'sand-rush' },
    { id: "annihilape", name: "Annihilape", spe: 90 },
    { id: "gholdengo", name: "Gholdengo", spe: 84 },
];
