import { Pokemon } from './types';

export const pokemonList: Pokemon[] = [
    // Gen 1
    { name: 'Venusaur', spe: 80, ability: 'chlorophyll' },
    { name: 'Mega Venusaur', spe: 80 },
    { name: 'Charizard', spe: 100 },
    { name: 'Mega Charizard X', spe: 100 },
    { name: 'Mega Charizard Y', spe: 100 },
    { name: 'Blastoise', spe: 78 },
    { name: 'Mega Blastoise', spe: 78 },
    { name: 'Beedrill', spe: 75 },
    { name: 'Mega Beedrill', spe: 145 },
    { name: 'Pidgeot', spe: 101 },
    { name: 'Mega Pidgeot', spe: 121 },
    { name: 'Arbok', spe: 80 },
    { name: 'Pikachu', spe: 90 },
    { name: 'Raichu', spe: 110 },
    { name: 'Alolan Raichu', spe: 110, ability: 'surge-surfer' },
    { name: 'Clefable', spe: 60 },
    { name: 'Mega Clefable', spe: 70 },
    { name: 'Ninetales', spe: 100 },
    { name: 'Alolan Ninetales', spe: 109 },
    { name: 'Arcanine', spe: 95 },
    { name: 'Hisuian Arcanine', spe: 90 },
    { name: 'Alakazam', spe: 120 },
    { name: 'Mega Alakazam', spe: 150 },
    { name: 'Machamp', spe: 55 },
    { name: 'Victreebel', spe: 70, ability: 'chlorophyll' },
    { name: 'Mega Victreebel', spe: 70 },
    { name: 'Slowbro', spe: 30 },
    { name: 'Mega Slowbro', spe: 30 },
    { name: 'Galarian Slowbro', spe: 30 },
    { name: 'Gengar', spe: 110 },
    { name: 'Mega Gengar', spe: 130 },
    { name: 'Kangaskhan', spe: 90 },
    { name: 'Mega Kangaskhan', spe: 100 },
    { name: 'Starmie', spe: 115 },
    { name: 'Mega Starmie', spe: 120 },
    { name: 'Pinsir', spe: 85 },
    { name: 'Mega Pinsir', spe: 105 },
    { name: 'Tauros', spe: 110 },
    { name: 'Paldean Tauros', spe: 100 },
    { name: 'Gyarados', spe: 81 },
    { name: 'Mega Gyarados', spe: 81 },
    { name: 'Ditto', spe: 48 },
    { name: 'Vaporeon', spe: 65 },
    { name: 'Jolteon', spe: 130, ability: 'quick-feet' },
    { name: 'Flareon', spe: 65 },
    { name: 'Aerodactyl', spe: 130 },
    { name: 'Mega Aerodactyl', spe: 150 },
    { name: 'Snorlax', spe: 30 },
    { name: 'Dragonite', spe: 80 },
    { name: 'Mega Dragonite', spe: 100 },

    // Gen 2
    { name: 'Meganium', spe: 80 },
    { name: 'Mega Meganium', spe: 80 },
    { name: 'Typhlosion', spe: 100 },
    { name: 'Hisuian Typhlosion', spe: 95 },
    { name: 'Feraligatr', spe: 78 },
    { name: 'Mega Feraligatr', spe: 78 },
    { name: 'Ariados', spe: 40 },
    { name: 'Ampharos', spe: 55 },
    { name: 'Mega Ampharos', spe: 45 },
    { name: 'Azumarill', spe: 50 },
    { name: 'Politoed', spe: 70 },
    { name: 'Espeon', spe: 110 },
    { name: 'Umbreon', spe: 65 },
    { name: 'Slowking', spe: 30 },
    { name: 'Galarian Slowking', spe: 30 },
    { name: 'Forretress', spe: 40 },
    { name: 'Steelix', spe: 30 },
    { name: 'Mega Steelix', spe: 30 },
    { name: 'Scizor', spe: 65 },
    { name: 'Mega Scizor', spe: 75 },
    { name: 'Heracross', spe: 85 },
    { name: 'Mega Heracross', spe: 75 },
    { name: 'Skarmory', spe: 70 },
    { name: 'Mega Skarmory', spe: 110 },
    { name: 'Houndoom', spe: 95 },
    { name: 'Mega Houndoom', spe: 115 },
    { name: 'Tyranitar', spe: 61 },
    { name: 'Mega Tyranitar', spe: 71 },

    // Gen 3
    { name: 'Pelipper', spe: 65 },
    { name: 'Gardevoir', spe: 80 },
    { name: 'Mega Gardevoir', spe: 100 },
    { name: 'Sableye', spe: 50 },
    { name: 'Mega Sableye', spe: 20 },
    { name: 'Aggron', spe: 50 },
    { name: 'Mega Aggron', spe: 50 },
    { name: 'Medicham', spe: 80 },
    { name: 'Mega Medicham', spe: 100 },
    { name: 'Manectric', spe: 105 },
    { name: 'Mega Manectric', spe: 135 },
    { name: 'Sharpedo', spe: 95 },
    { name: 'Mega Sharpedo', spe: 105 },
    { name: 'Camerupt', spe: 40 },
    { name: 'Mega Camerupt', spe: 20 },
    { name: 'Torkoal', spe: 20 },
    { name: 'Altaria', spe: 80 },
    { name: 'Mega Altaria', spe: 80 },
    { name: 'Milotic', spe: 81 },
    { name: 'Castform', spe: 70 },
    { name: 'Banette', spe: 65 },
    { name: 'Mega Banette', spe: 75 },
    { name: 'Chimecho', spe: 65 },
    { name: 'Mega Chimecho', spe: 65 },
    { name: 'Absol', spe: 75 },
    { name: 'Mega Absol', spe: 115 },
    { name: 'Glalie', spe: 80 },
    { name: 'Mega Glalie', spe: 100 },

    // Gen 4
    { name: 'Torterra', spe: 56 },
    { name: 'Infernape', spe: 108 },
    { name: 'Empoleon', spe: 60 },
    { name: 'Luxray', spe: 70 },
    { name: 'Roserade', spe: 90 },
    { name: 'Rampardos', spe: 58 },
    { name: 'Bastiodon', spe: 30 },
    { name: 'Lopunny', spe: 105 },
    { name: 'Mega Lopunny', spe: 135 },
    { name: 'Spiritomb', spe: 35 },
    { name: 'Garchomp', spe: 102 },
    { name: 'Mega Garchomp', spe: 92 },
    { name: 'Lucario', spe: 90 },
    { name: 'Mega Lucario', spe: 112 },
    { name: 'Hippowdon', spe: 47 },
    { name: 'Toxicroak', spe: 85 },
    { name: 'Abomasnow', spe: 60 },
    { name: 'Mega Abomasnow', spe: 30 },
    { name: 'Weavile', spe: 125 },
    { name: 'Rhyperior', spe: 40 },
    { name: 'Leafeon', spe: 95, ability: 'chlorophyll' },
    { name: 'Glaceon', spe: 65 },
    { name: 'Gliscor', spe: 95 },
    { name: 'Mamoswine', spe: 80 },
    { name: 'Gallade', spe: 80 },
    { name: 'Mega Gallade', spe: 110 },
    { name: 'Froslass', spe: 110 },
    { name: 'Mega Froslass', spe: 120 },
    { name: 'Rotom', spe: 91 },

    // Gen 5
    { name: 'Serperior', spe: 113 },
    { name: 'Emboar', spe: 65 },
    { name: 'Mega Emboar', spe: 75 },
    { name: 'Samurott', spe: 70 },
    { name: 'Hisuian Samurott', spe: 85 },
    { name: 'Watchog', spe: 77 },
    { name: 'Liepard', spe: 106, ability: 'unburden' },
    { name: 'Simisage', spe: 101 },
    { name: 'Simisear', spe: 101 },
    { name: 'Simipour', spe: 101 },
    { name: 'Excadrill', spe: 88, ability: 'sand-rush' },
    { name: 'Mega Excadrill', spe: 103 },
    { name: 'Audino', spe: 50 },
    { name: 'Mega Audino', spe: 50 },
    { name: 'Conkeldurr', spe: 45 },
    { name: 'Whimsicott', spe: 116, ability: 'chlorophyll' },
    { name: 'Krookodile', spe: 92 },
    { name: 'Cofagrigus', spe: 30 },
    { name: 'Garbodor', spe: 75 },
    { name: 'Zoroark', spe: 105 },
    { name: 'Hisuian Zoroark', spe: 110 },
    { name: 'Reuniclus', spe: 30 },
    { name: 'Vanilluxe', spe: 79 },
    { name: 'Emolga', spe: 103 },
    { name: 'Chandelure', spe: 80 },
    { name: 'Mega Chandelure', spe: 90 },
    { name: 'Beartic', spe: 50, ability: ['swift-swim', 'slush-rush'] },
    { name: 'Stunfisk', spe: 32 },
    { name: 'Galarian Stunfisk', spe: 32 },
    { name: 'Golurk', spe: 55 },
    { name: 'Mega Golurk', spe: 55 },
    { name: 'Hydreigon', spe: 98 },
    { name: 'Volcarona', spe: 100 },

    // Gen 6
    { name: 'Chesnaught', spe: 64 },
    { name: 'Mega Chesnaught', spe: 44 },
    { name: 'Delphox', spe: 104 },
    { name: 'Mega Delphox', spe: 134 },
    { name: 'Greninja', spe: 122 },
    { name: 'Mega Greninja', spe: 142 },
    { name: 'Diggersby', spe: 78 },
    { name: 'Talonflame', spe: 126 },
    { name: 'Vivillon', spe: 89 },
    { name: 'Floette-Eternal', spe: 92 },
    { name: 'Mega Floette', spe: 102 },
    { name: 'Florges', spe: 75 },
    { name: 'Pangoro', spe: 58 },
    { name: 'Furfrou', spe: 102 },
    { name: 'Meowstic', spe: 104 },
    { name: 'Mega Meowstic', spe: 124 },
    { name: 'Aegislash', spe: 60 },
    { name: 'Aromatisse', spe: 29 },
    { name: 'Slurpuff', spe: 72, ability: 'unburden' },
    { name: 'Clawitzer', spe: 59 },
    { name: 'Heliolisk', spe: 109 },
    { name: 'Tyrantrum', spe: 71 },
    { name: 'Aurorus', spe: 58 },
    { name: 'Sylveon', spe: 60 },
    { name: 'Hawlucha', spe: 118, ability: 'unburden' },
    { name: 'Mega Hawlucha', spe: 118 },
    { name: 'Dedenne', spe: 101 },
    { name: 'Goodra', spe: 80 },
    { name: 'Hisuian Goodra', spe: 60 },
    { name: 'Klefki', spe: 75 },
    { name: 'Trevenant', spe: 56 },
    { name: 'Gourgeist', spe: 84 },
    { name: 'Avalugg', spe: 28 },
    { name: 'Hisuian Avalugg', spe: 38 },
    { name: 'Noivern', spe: 123 },

    // Gen 7
    { name: 'Decidueye', spe: 70 },
    { name: 'Hisuian Decidueye', spe: 60 },
    { name: 'Incineroar', spe: 60 },
    { name: 'Primarina', spe: 60 },
    { name: 'Toucannon', spe: 60 },
    { name: 'Crabominable', spe: 43 },
    { name: 'Mega Crabominable', spe: 33 },
    { name: 'Lycanroc', spe: 112, ability: 'sand-rush' },
    { name: 'Toxapex', spe: 35 },
    { name: 'Mudsdale', spe: 35 },
    { name: 'Araquanid', spe: 42 },
    { name: 'Salazzle', spe: 117 },
    { name: 'Tsareena', spe: 72 },
    { name: 'Oranguru', spe: 60 },
    { name: 'Passimian', spe: 80 },
    { name: 'Mimikyu', spe: 96 },
    { name: 'Drampa', spe: 36 },
    { name: 'Mega Drampa', spe: 36 },
    { name: 'Kommo-o', spe: 85 },

    // Gen 8
    { name: 'Corviknight', spe: 67 },
    { name: 'Flapple', spe: 70 },
    { name: 'Appletun', spe: 30 },
    { name: 'Sandaconda', spe: 71 },
    { name: 'Polteageist', spe: 70 },
    { name: 'Hatterene', spe: 29 },
    { name: 'Mr. Rime', spe: 70 },
    { name: 'Runerigus', spe: 30 },
    { name: 'Alcremie', spe: 64 },
    { name: 'Morpeko', spe: 97 },
    { name: 'Dragapult', spe: 142 },

    // Legends: Arceus
    { name: 'Wyrdeer', spe: 65 },
    { name: 'Kleavor', spe: 85 },
    { name: 'Basculegion', spe: 78, ability: 'swift-swim' },
    { name: 'Sneasler', spe: 120, ability: 'unburden' },

    // Gen 9
    { name: 'Meowscarada', spe: 123 },
    { name: 'Skeledirge', spe: 66 },
    { name: 'Quaquaval', spe: 85 },
    { name: 'Maushold', spe: 111 },
    { name: 'Garganacl', spe: 35 },
    { name: 'Armarouge', spe: 75 },
    { name: 'Ceruledge', spe: 85 },
    { name: 'Bellibolt', spe: 45 },
    { name: 'Scovillain', spe: 75, ability: 'chlorophyll' },
    { name: 'Mega Scovillain', spe: 75 },
    { name: 'Espathra', spe: 105 },
    { name: 'Tinkaton', spe: 94 },
    { name: 'Palafin', spe: 100 },
    { name: 'Orthworm', spe: 65 },
    { name: 'Glimmora', spe: 86 },
    { name: 'Mega Glimmora', spe: 101 },
    { name: 'Farigiraf', spe: 60 },
    { name: 'Kingambit', spe: 50 },
    { name: 'Sinistcha', spe: 70 },
    { name: 'Archaludon', spe: 85 },
    { name: 'Hydrapple', spe: 44 },
];
