import { Pokemon } from './types';

export const pokemonList: Pokemon[] = [
    // Gen 1
    { id: "venusaur", name: "Venusaur", spe: 80, ability: 'chlorophyll' },
    { id: "mega venusaur", name: "Mega Venusaur", spe: 80, baseSpecies: "venusaur" },
    { id: "charizard", name: "Charizard", spe: 100 },
    { id: "mega charizard x", name: "Mega Charizard X", spe: 100, baseSpecies: "charizard" },
    { id: "mega charizard y", name: "Mega Charizard Y", spe: 100, baseSpecies: "charizard" },
    { id: "blastoise", name: "Blastoise", spe: 78 },
    { id: "mega blastoise", name: "Mega Blastoise", spe: 78, baseSpecies: "blastoise" },
    { id: "beedrill", name: "Beedrill", spe: 75 },
    { id: "mega beedrill", name: "Mega Beedrill", spe: 145, baseSpecies: "beedrill" },
    { id: "pidgeot", name: "Pidgeot", spe: 101 },
    { id: "mega pidgeot", name: "Mega Pidgeot", spe: 121, baseSpecies: "pidgeot" },
    { id: "arbok", name: "Arbok", spe: 80 },
    { id: "pikachu", name: "Pikachu", spe: 90 },
    { id: "raichu", name: "Raichu", spe: 110 },
    { id: "alolan raichu", name: "Alolan Raichu", spe: 110, ability: 'surge-surfer', baseSpecies: "raichu" },
    { id: "clefable", name: "Clefable", spe: 60 },
    { id: "mega clefable", name: "Mega Clefable", spe: 70, baseSpecies: "clefable" },
    { id: "ninetales", name: "Ninetales", spe: 100 },
    { id: "alolan ninetales", name: "Alolan Ninetales", spe: 109, baseSpecies: "ninetales" },
    { id: "arcanine", name: "Arcanine", spe: 95 },
    { id: "hisuian arcanine", name: "Hisuian Arcanine", spe: 90, baseSpecies: "arcanine" },
    { id: "alakazam", name: "Alakazam", spe: 120 },
    { id: "mega alakazam", name: "Mega Alakazam", spe: 150, baseSpecies: "alakazam" },
    { id: "machamp", name: "Machamp", spe: 55 },
    { id: "victreebel", name: "Victreebel", spe: 70, ability: 'chlorophyll' },
    { id: "mega victreebel", name: "Mega Victreebel", spe: 70, baseSpecies: "victreebel" },
    { id: "slowbro", name: "Slowbro", spe: 30 },
    { id: "mega slowbro", name: "Mega Slowbro", spe: 30, baseSpecies: "slowbro" },
    { id: "galarian slowbro", name: "Galarian Slowbro", spe: 30, baseSpecies: "slowbro" },
    { id: "gengar", name: "Gengar", spe: 110 },
    { id: "mega gengar", name: "Mega Gengar", spe: 130, baseSpecies: "gengar" },
    { id: "kangaskhan", name: "Kangaskhan", spe: 90 },
    { id: "mega kangaskhan", name: "Mega Kangaskhan", spe: 100, baseSpecies: "kangaskhan" },
    { id: "starmie", name: "Starmie", spe: 115 },
    { id: "mega starmie", name: "Mega Starmie", spe: 120, baseSpecies: "starmie" },
    { id: "pinsir", name: "Pinsir", spe: 85 },
    { id: "mega pinsir", name: "Mega Pinsir", spe: 105, baseSpecies: "pinsir" },
    { id: "tauros", name: "Tauros", spe: 110 },
    { id: "paldean tauros", name: "Paldean Tauros", spe: 100, baseSpecies: "tauros" },
    { id: "gyarados", name: "Gyarados", spe: 81 },
    { id: "mega gyarados", name: "Mega Gyarados", spe: 81, baseSpecies: "gyarados" },
    { id: "ditto", name: "Ditto", spe: 48 },
    { id: "vaporeon", name: "Vaporeon", spe: 65 },
    { id: "jolteon", name: "Jolteon", spe: 130, ability: 'quick-feet' },
    { id: "flareon", name: "Flareon", spe: 65 },
    { id: "aerodactyl", name: "Aerodactyl", spe: 130 },
    { id: "mega aerodactyl", name: "Mega Aerodactyl", spe: 150, baseSpecies: "aerodactyl" },
    { id: "snorlax", name: "Snorlax", spe: 30 },
    { id: "dragonite", name: "Dragonite", spe: 80 },
    { id: "mega dragonite", name: "Mega Dragonite", spe: 100, baseSpecies: "dragonite" },

    // Gen 2
    { id: "meganium", name: "Meganium", spe: 80 },
    { id: "mega meganium", name: "Mega Meganium", spe: 80, baseSpecies: "meganium" },
    { id: "typhlosion", name: "Typhlosion", spe: 100 },
    { id: "hisuian typhlosion", name: "Hisuian Typhlosion", spe: 95, baseSpecies: "typhlosion" },
    { id: "feraligatr", name: "Feraligatr", spe: 78 },
    { id: "mega feraligatr", name: "Mega Feraligatr", spe: 78, baseSpecies: "feraligatr" },
    { id: "ariados", name: "Ariados", spe: 40 },
    { id: "ampharos", name: "Ampharos", spe: 55 },
    { id: "mega ampharos", name: "Mega Ampharos", spe: 45, baseSpecies: "ampharos" },
    { id: "azumarill", name: "Azumarill", spe: 50 },
    { id: "politoed", name: "Politoed", spe: 70 },
    { id: "espeon", name: "Espeon", spe: 110 },
    { id: "umbreon", name: "Umbreon", spe: 65 },
    { id: "slowking", name: "Slowking", spe: 30 },
    { id: "galarian slowking", name: "Galarian Slowking", spe: 30, baseSpecies: "slowking" },
    { id: "forretress", name: "Forretress", spe: 40 },
    { id: "steelix", name: "Steelix", spe: 30 },
    { id: "mega steelix", name: "Mega Steelix", spe: 30, baseSpecies: "steelix" },
    { id: "scizor", name: "Scizor", spe: 65 },
    { id: "mega scizor", name: "Mega Scizor", spe: 75, baseSpecies: "scizor" },
    { id: "heracross", name: "Heracross", spe: 85 },
    { id: "mega heracross", name: "Mega Heracross", spe: 75, baseSpecies: "heracross" },
    { id: "skarmory", name: "Skarmory", spe: 70 },
    { id: "mega skarmory", name: "Mega Skarmory", spe: 110, baseSpecies: "skarmory" },
    { id: "houndoom", name: "Houndoom", spe: 95 },
    { id: "mega houndoom", name: "Mega Houndoom", spe: 115, baseSpecies: "houndoom" },
    { id: "tyranitar", name: "Tyranitar", spe: 61 },
    { id: "mega tyranitar", name: "Mega Tyranitar", spe: 71, baseSpecies: "tyranitar" },

    // Gen 3
    { id: "pelipper", name: "Pelipper", spe: 65 },
    { id: "gardevoir", name: "Gardevoir", spe: 80 },
    { id: "mega gardevoir", name: "Mega Gardevoir", spe: 100, baseSpecies: "gardevoir" },
    { id: "sableye", name: "Sableye", spe: 50 },
    { id: "mega sableye", name: "Mega Sableye", spe: 20, baseSpecies: "sableye" },
    { id: "aggron", name: "Aggron", spe: 50 },
    { id: "mega aggron", name: "Mega Aggron", spe: 50, baseSpecies: "aggron" },
    { id: "medicham", name: "Medicham", spe: 80 },
    { id: "mega medicham", name: "Mega Medicham", spe: 100, baseSpecies: "medicham" },
    { id: "manectric", name: "Manectric", spe: 105 },
    { id: "mega manectric", name: "Mega Manectric", spe: 135, baseSpecies: "manectric" },
    { id: "sharpedo", name: "Sharpedo", spe: 95 },
    { id: "mega sharpedo", name: "Mega Sharpedo", spe: 105, baseSpecies: "sharpedo" },
    { id: "camerupt", name: "Camerupt", spe: 40 },
    { id: "mega camerupt", name: "Mega Camerupt", spe: 20, baseSpecies: "camerupt" },
    { id: "torkoal", name: "Torkoal", spe: 20 },
    { id: "altaria", name: "Altaria", spe: 80 },
    { id: "mega altaria", name: "Mega Altaria", spe: 80, baseSpecies: "altaria" },
    { id: "milotic", name: "Milotic", spe: 81 },
    { id: "castform", name: "Castform", spe: 70 },
    { id: "banette", name: "Banette", spe: 65 },
    { id: "mega banette", name: "Mega Banette", spe: 75, baseSpecies: "banette" },
    { id: "chimecho", name: "Chimecho", spe: 65 },
    { id: "mega chimecho", name: "Mega Chimecho", spe: 65, baseSpecies: "chimecho" },
    { id: "absol", name: "Absol", spe: 75 },
    { id: "mega absol", name: "Mega Absol", spe: 115, baseSpecies: "absol" },
    { id: "glalie", name: "Glalie", spe: 80 },
    { id: "mega glalie", name: "Mega Glalie", spe: 100, baseSpecies: "glalie" },

    // Gen 4
    { id: "torterra", name: "Torterra", spe: 56 },
    { id: "infernape", name: "Infernape", spe: 108 },
    { id: "empoleon", name: "Empoleon", spe: 60 },
    { id: "luxray", name: "Luxray", spe: 70 },
    { id: "roserade", name: "Roserade", spe: 90 },
    { id: "rampardos", name: "Rampardos", spe: 58 },
    { id: "bastiodon", name: "Bastiodon", spe: 30 },
    { id: "lopunny", name: "Lopunny", spe: 105 },
    { id: "mega lopunny", name: "Mega Lopunny", spe: 135, baseSpecies: "lopunny" },
    { id: "spiritomb", name: "Spiritomb", spe: 35 },
    { id: "garchomp", name: "Garchomp", spe: 102 },
    { id: "mega garchomp", name: "Mega Garchomp", spe: 92, baseSpecies: "garchomp" },
    { id: "lucario", name: "Lucario", spe: 90 },
    { id: "mega lucario", name: "Mega Lucario", spe: 112, baseSpecies: "lucario" },
    { id: "hippowdon", name: "Hippowdon", spe: 47 },
    { id: "toxicroak", name: "Toxicroak", spe: 85 },
    { id: "abomasnow", name: "Abomasnow", spe: 60 },
    { id: "mega abomasnow", name: "Mega Abomasnow", spe: 30, baseSpecies: "abomasnow" },
    { id: "weavile", name: "Weavile", spe: 125 },
    { id: "rhyperior", name: "Rhyperior", spe: 40 },
    { id: "leafeon", name: "Leafeon", spe: 95, ability: 'chlorophyll' },
    { id: "glaceon", name: "Glaceon", spe: 65 },
    { id: "gliscor", name: "Gliscor", spe: 95 },
    { id: "mamoswine", name: "Mamoswine", spe: 80 },
    { id: "gallade", name: "Gallade", spe: 80 },
    { id: "mega gallade", name: "Mega Gallade", spe: 110, baseSpecies: "gallade" },
    { id: "froslass", name: "Froslass", spe: 110 },
    { id: "mega froslass", name: "Mega Froslass", spe: 120, baseSpecies: "froslass" },
    { id: "rotom", name: "Rotom", spe: 91 },

    // Gen 5
    { id: "serperior", name: "Serperior", spe: 113 },
    { id: "emboar", name: "Emboar", spe: 65 },
    { id: "mega emboar", name: "Mega Emboar", spe: 75, baseSpecies: "emboar" },
    { id: "samurott", name: "Samurott", spe: 70 },
    { id: "hisuian samurott", name: "Hisuian Samurott", spe: 85, baseSpecies: "samurott" },
    { id: "watchog", name: "Watchog", spe: 77 },
    { id: "liepard", name: "Liepard", spe: 106, ability: 'unburden' },
    { id: "simisage", name: "Simisage", spe: 101 },
    { id: "simisear", name: "Simisear", spe: 101 },
    { id: "simipour", name: "Simipour", spe: 101 },
    { id: "excadrill", name: "Excadrill", spe: 88, ability: 'sand-rush' },
    { id: "mega excadrill", name: "Mega Excadrill", spe: 103, baseSpecies: "excadrill" },
    { id: "audino", name: "Audino", spe: 50 },
    { id: "mega audino", name: "Mega Audino", spe: 50, baseSpecies: "audino" },
    { id: "conkeldurr", name: "Conkeldurr", spe: 45 },
    { id: "whimsicott", name: "Whimsicott", spe: 116, ability: 'chlorophyll' },
    { id: "krookodile", name: "Krookodile", spe: 92 },
    { id: "cofagrigus", name: "Cofagrigus", spe: 30 },
    { id: "garbodor", name: "Garbodor", spe: 75 },
    { id: "zoroark", name: "Zoroark", spe: 105 },
    { id: "hisuian zoroark", name: "Hisuian Zoroark", spe: 110, baseSpecies: "zoroark" },
    { id: "reuniclus", name: "Reuniclus", spe: 30 },
    { id: "vanilluxe", name: "Vanilluxe", spe: 79 },
    { id: "emolga", name: "Emolga", spe: 103 },
    { id: "chandelure", name: "Chandelure", spe: 80 },
    { id: "mega chandelure", name: "Mega Chandelure", spe: 90, baseSpecies: "chandelure" },
    { id: "beartic", name: "Beartic", spe: 50, ability: ['swift-swim', 'slush-rush'] },
    { id: "stunfisk", name: "Stunfisk", spe: 32 },
    { id: "galarian stunfisk", name: "Galarian Stunfisk", spe: 32, baseSpecies: "stunfisk" },
    { id: "golurk", name: "Golurk", spe: 55 },
    { id: "mega golurk", name: "Mega Golurk", spe: 55, baseSpecies: "golurk" },
    { id: "hydreigon", name: "Hydreigon", spe: 98 },
    { id: "volcarona", name: "Volcarona", spe: 100 },

    // Gen 6
    { id: "chesnaught", name: "Chesnaught", spe: 64 },
    { id: "mega chesnaught", name: "Mega Chesnaught", spe: 44, baseSpecies: "chesnaught" },
    { id: "delphox", name: "Delphox", spe: 104 },
    { id: "mega delphox", name: "Mega Delphox", spe: 134, baseSpecies: "delphox" },
    { id: "greninja", name: "Greninja", spe: 122 },
    { id: "mega greninja", name: "Mega Greninja", spe: 142, baseSpecies: "greninja" },
    { id: "diggersby", name: "Diggersby", spe: 78 },
    { id: "talonflame", name: "Talonflame", spe: 126 },
    { id: "vivillon", name: "Vivillon", spe: 89 },
    { id: "floette-eternal", name: "Floette-Eternal", spe: 92, baseSpecies: "floette" },
    { id: "mega floette", name: "Mega Floette", spe: 102, baseSpecies: "floette" },
    { id: "florges", name: "Florges", spe: 75 },
    { id: "pangoro", name: "Pangoro", spe: 58 },
    { id: "furfrou", name: "Furfrou", spe: 102 },
    { id: "meowstic", name: "Meowstic", spe: 104 },
    { id: "mega meowstic", name: "Mega Meowstic", spe: 124, baseSpecies: "meowstic" },
    { id: "aegislash", name: "Aegislash", spe: 60 },
    { id: "aromatisse", name: "Aromatisse", spe: 29 },
    { id: "slurpuff", name: "Slurpuff", spe: 72, ability: 'unburden' },
    { id: "clawitzer", name: "Clawitzer", spe: 59 },
    { id: "heliolisk", name: "Heliolisk", spe: 109 },
    { id: "tyrantrum", name: "Tyrantrum", spe: 71 },
    { id: "aurorus", name: "Aurorus", spe: 58 },
    { id: "sylveon", name: "Sylveon", spe: 60 },
    { id: "hawlucha", name: "Hawlucha", spe: 118, ability: 'unburden' },
    { id: "mega hawlucha", name: "Mega Hawlucha", spe: 118, baseSpecies: "hawlucha" },
    { id: "dedenne", name: "Dedenne", spe: 101 },
    { id: "goodra", name: "Goodra", spe: 80 },
    { id: "hisuian goodra", name: "Hisuian Goodra", spe: 60, baseSpecies: "goodra" },
    { id: "klefki", name: "Klefki", spe: 75 },
    { id: "trevenant", name: "Trevenant", spe: 56 },
    { id: "gourgeist", name: "Gourgeist", spe: 84 },
    { id: "avalugg", name: "Avalugg", spe: 28 },
    { id: "hisuian avalugg", name: "Hisuian Avalugg", spe: 38, baseSpecies: "avalugg" },
    { id: "noivern", name: "Noivern", spe: 123 },

    // Gen 7
    { id: "decidueye", name: "Decidueye", spe: 70 },
    { id: "hisuian decidueye", name: "Hisuian Decidueye", spe: 60, baseSpecies: "decidueye" },
    { id: "incineroar", name: "Incineroar", spe: 60 },
    { id: "primarina", name: "Primarina", spe: 60 },
    { id: "toucannon", name: "Toucannon", spe: 60 },
    { id: "crabominable", name: "Crabominable", spe: 43 },
    { id: "mega crabominable", name: "Mega Crabominable", spe: 33, baseSpecies: "crabominable" },
    { id: "lycanroc", name: "Lycanroc", spe: 112, ability: 'sand-rush' },
    { id: "toxapex", name: "Toxapex", spe: 35 },
    { id: "mudsdale", name: "Mudsdale", spe: 35 },
    { id: "araquanid", name: "Araquanid", spe: 42 },
    { id: "salazzle", name: "Salazzle", spe: 117 },
    { id: "tsareena", name: "Tsareena", spe: 72 },
    { id: "oranguru", name: "Oranguru", spe: 60 },
    { id: "passimian", name: "Passimian", spe: 80 },
    { id: "mimikyu", name: "Mimikyu", spe: 96 },
    { id: "drampa", name: "Drampa", spe: 36 },
    { id: "mega drampa", name: "Mega Drampa", spe: 36, baseSpecies: "drampa" },
    { id: "kommo-o", name: "Kommo-o", spe: 85 },

    // Gen 8
    { id: "corviknight", name: "Corviknight", spe: 67 },
    { id: "flapple", name: "Flapple", spe: 70 },
    { id: "appletun", name: "Appletun", spe: 30 },
    { id: "sandaconda", name: "Sandaconda", spe: 71 },
    { id: "polteageist", name: "Polteageist", spe: 70 },
    { id: "hatterene", name: "Hatterene", spe: 29 },
    { id: "mr. rime", name: "Mr. Rime", spe: 70 },
    { id: "runerigus", name: "Runerigus", spe: 30 },
    { id: "alcremie", name: "Alcremie", spe: 64 },
    { id: "morpeko", name: "Morpeko", spe: 97 },
    { id: "dragapult", name: "Dragapult", spe: 142 },

    // Legends: Arceus
    { id: "wyrdeer", name: "Wyrdeer", spe: 65 },
    { id: "kleavor", name: "Kleavor", spe: 85 },
    { id: "basculegion", name: "Basculegion", spe: 78, ability: 'swift-swim' },
    { id: "sneasler", name: "Sneasler", spe: 120, ability: 'unburden' },

    // Gen 9
    { id: "meowscarada", name: "Meowscarada", spe: 123 },
    { id: "skeledirge", name: "Skeledirge", spe: 66 },
    { id: "quaquaval", name: "Quaquaval", spe: 85 },
    { id: "maushold", name: "Maushold", spe: 111 },
    { id: "garganacl", name: "Garganacl", spe: 35 },
    { id: "armarouge", name: "Armarouge", spe: 75 },
    { id: "ceruledge", name: "Ceruledge", spe: 85 },
    { id: "bellibolt", name: "Bellibolt", spe: 45 },
    { id: "scovillain", name: "Scovillain", spe: 75, ability: 'chlorophyll' },
    { id: "mega scovillain", name: "Mega Scovillain", spe: 75, baseSpecies: "scovillain" },
    { id: "espathra", name: "Espathra", spe: 105 },
    { id: "tinkaton", name: "Tinkaton", spe: 94 },
    { id: "palafin", name: "Palafin", spe: 100 },
    { id: "orthworm", name: "Orthworm", spe: 65 },
    { id: "glimmora", name: "Glimmora", spe: 86 },
    { id: "mega glimmora", name: "Mega Glimmora", spe: 101, baseSpecies: "glimmora" },
    { id: "farigiraf", name: "Farigiraf", spe: 60 },
    { id: "kingambit", name: "Kingambit", spe: 50 },
    { id: "sinistcha", name: "Sinistcha", spe: 70 },
    { id: "archaludon", name: "Archaludon", spe: 85 },
    { id: "hydrapple", name: "Hydrapple", spe: 44 },
];
